export LANG=en_US.UTF-8
export LC_NUMERIC="en_US.UTF-8"
CASE_SENSITIVE="true"

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nano'
fi

export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTFILE=~/zsh_history/.zsh_history

if [[ ! -d ~/zsh_history ]]; then
  mkdir -p ~/zsh_history
fi
touch $HISTFILE

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
zstyle ':omz:update' mode disabled

plugins=(
  git
  git-extras
  git-flow
  colorize
  command-not-found
  common-aliases
  zsh-syntax-highlighting
  zsh-autosuggestions
  sudo
  colored-man-pages
)

source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

unalias rm 2>/dev/null || true
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias zshrc='nano ~/.zshrc'
alias ros2init='source /opt/ros/lyrical/setup.zsh && source /workspace/install/local_setup.zsh'
alias python='python3'

export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

if [ -f "$HOME/.local/bin/env" ]; then
  . "$HOME/.local/bin/env"
fi
