name: Semantic Fleet Brain CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ==========================================
  # JOB 1: Cloud Backend (FastAPI & Python)
  # ==========================================
  api_tests:
    name: Test FastAPI Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest

      - name: Run Pytest
        run: |
          echo "Here we will run: pytest tests/api/"

  # ==========================================
  # JOB 2: Edge (ROS2 C++ & Python compilation)
  # ==========================================
  ros2_build:
    name: Build ROS2 Workspace
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Environment
        run: |
          docker build -t semantic-fleet-brain-env -f docker/Dockerfile .

      - name: Run Colcon Build inside Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -u $(id -u):$(id -g) \
            semantic-fleet-brain-env \
            /bin/bash -c "cd /workspace && colcon build --packages-select semantic_sim_env"
